import Config

# ! general

# Do not print debug messages in production.
config :logger, level: :info

# ! core

# Configure the mailer
#
# Setup Swoosh API client.
config :swoosh,
  api_client: Swoosh.ApiClient.Finch,
  finch_name: ComboSaaS.Core.Finch

# Disable Swoosh local memory storage.
config :swoosh, local: false

# ! user_web

# Note we also include the path to a cache manifest containing the digested
# version of static files. This manifest is generated by the `mix phx.digest`
# task, which you should run after static files are built and before starting
# the production server.
config :combo_saas, ComboSaaS.UserWeb.Endpoint,
  cache_static_manifest: "priv/user_web/static/cache_manifest.json"

# ! user_api

# nothing to do

# ! admin_web

# Note we also include the path to a cache manifest containing the digested
# version of static files. This manifest is generated by the `mix phx.digest`
# task, which you should run after static files are built and before starting
# the production server.
config :combo_saas, ComboSaaS.AdminWeb.Endpoint,
  cache_static_manifest: "priv/admin_web/static/cache_manifest.json"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
