import Config

# ! general

# Do not print debug messages.
config :logger, level: :info

# ! core

# nothing to do

# ! user_web

# Note we also include the path to a cache manifest containing the digested
# version of static files. This manifest is generated by the `mix phx.digest`
# task, which you should run after static files are built and before starting
# the production server.
config :combo_desktop, ComboDesktop.UserWeb.Endpoint,
  cache_static_manifest: "priv/user_web/static/cache_manifest.json"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
